#!/bin/bash
set -euo pipefail

# shellcheck disable=SC2034
declare -r DEPLOY_VERSION="0.1.0"

DEPLOY_ROOT_DIR="$(dirname "${BASH_SOURCE[0]}")"
export DEPLOY_ROOT_DIR

source "$DEPLOY_ROOT_DIR/src/dev/debug.sh"
source "$DEPLOY_ROOT_DIR/src/colors.sh"
source "$DEPLOY_ROOT_DIR/src/compare.sh"
source "$DEPLOY_ROOT_DIR/src/env_configuration.sh"
source "$DEPLOY_ROOT_DIR/src/io.sh"
source "$DEPLOY_ROOT_DIR/src/release.sh"
source "$DEPLOY_ROOT_DIR/src/validate.sh"
source "$DEPLOY_ROOT_DIR/src/main.sh"

# Check if at least one argument (branch name) is passed
if [ $# -lt 1 ]; then
    echo "Usage: deploy [branch name] [--force (optional)]"
    echo "Arguments"
    echo "  branch name to deploy"
    echo "Options"
    echo "  --force ignore that your current branch as ahead commits"
    echo ""
    echo "Examples:
- deploy main
- deploy hotfix/...
- deploy hotfix/... --force"
    exit 1
fi

FORCE_DEPLOY=false
SOURCE_BRANCH=$1
TARGET_BRANCH=${2:-}
DEVELOPMENT_BRANCH=${3:-}
DRY_RUN=${DRY_RUN:-false}

while [[ $# -gt 0 ]]; do
  argument="$1"
  case $argument in
    --debug)
      set -x
      ;;
    --dry-run)
      DRY_RUN=true
      ;;
    -e|--env)
      # shellcheck disable=SC1090
      source "$2"
      shift
      ;;
    -s|--source)
      SOURCE_BRANCH="$2"
      shift
      ;;
    -t|--target)
      TARGET_BRANCH="$2"
      shift
      ;;
    -d|--development)
      DEVELOPMENT_BRANCH="$2"
      shift
      ;;
    --force)
      FORCE_DEPLOY=true
      ;;
  esac
  shift
done

GH_CLI_INSTALLED=false
if command -v gh &> /dev/null; then
    GH_CLI_INSTALLED=true
fi

export GH_CLI_INSTALLED
export DRY_RUN

TARGET_BRANCH=${TARGET_BRANCH:-"prod"}
DEVELOPMENT_BRANCH=${DEVELOPMENT_BRANCH:-"main"}
DEPLOY_SUCCESSFUL_TEXT=${DEPLOY_SUCCESSFUL_TEXT:-}

main::action "$SOURCE_BRANCH" \
  "$TARGET_BRANCH" \
  "$DEVELOPMENT_BRANCH" \
  "$FORCE_DEPLOY" \
  "$DEPLOY_SUCCESSFUL_TEXT"

echo "Script finished successfully."
