#!/bin/bash
set -euo pipefail

# shellcheck disable=SC2034
declare -r DEPLOY_VERSION="0.1.0"

DEPLOY_ROOT_DIR="$(dirname "${BASH_SOURCE[0]}")"
export DEPLOY_ROOT_DIR

source "$DEPLOY_ROOT_DIR/src/dev/debug.sh"
source "$DEPLOY_ROOT_DIR/src/colors.sh"
source "$DEPLOY_ROOT_DIR/src/compare.sh"
source "$DEPLOY_ROOT_DIR/src/console_header.sh"
source "$DEPLOY_ROOT_DIR/src/env_configuration.sh"
source "$DEPLOY_ROOT_DIR/src/io.sh"
source "$DEPLOY_ROOT_DIR/src/release.sh"
source "$DEPLOY_ROOT_DIR/src/validate.sh"
source "$DEPLOY_ROOT_DIR/src/main.sh"

# Check if at least one argument (branch name) is passed
if [ $# -lt 1 ]; then
  console_header::print_help
  exit 1
fi

FORCE_DEPLOY=false
SOURCE_BRANCH=${SOURCE_BRANCH:-"main"}
TARGET_BRANCH=${TARGET_BRANCH:-"prod"}
DEVELOPMENT_BRANCH=${DEVELOPMENT_BRANCH:-"main"}
DEPLOY_SUCCESSFUL_TEXT=${DEPLOY_SUCCESSFUL_TEXT:-}
DRY_RUN=${DRY_RUN:-false}

while [[ $# -gt 0 ]]; do
  argument="$1"
  case $argument in
    --debug)
      set -x
      ;;
    --dry-run)
      DRY_RUN=true
      ;;
    -s|--source)
      SOURCE_BRANCH="$2"
      shift
      ;;
    -t|--target)
      TARGET_BRANCH="$2"
      shift
      ;;
    -d|--development)
      DEVELOPMENT_BRANCH="$2"
      shift
      ;;
    --force)
      FORCE_DEPLOY=true
      ;;
  esac
  shift
done

GH_CLI_INSTALLED=false
if command -v gh &> /dev/null; then
    GH_CLI_INSTALLED=true
fi

export GH_CLI_INSTALLED
export DRY_RUN


main::action "$SOURCE_BRANCH" \
  "$TARGET_BRANCH" \
  "$DEVELOPMENT_BRANCH" \
  "$FORCE_DEPLOY" \
  "$DEPLOY_SUCCESSFUL_TEXT"

echo "Script finished successfully."
